- name: Generate cluster CA and certificates
  hosts: localhost
  connection: local
  gather_facts: false
  pre_tasks:
    - ansible.builtin.import_tasks: tasks/read_terraform_outputs.yml
  roles:
    - ca
    - component-certs
    - apiserver-cert
    - etcd-cert
