- name: Generate cluster kubeconfigs
  hosts: localhost
  connection: local
  gather_facts: false
  pre_tasks:
    - name: Read Terraform outputs
      ansible.builtin.import_tasks: tasks/read_terraform_outputs.yml
  roles:
    - kubeconfig
