// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: exif_metadata.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getExifMetadataByObjectID = `-- name: GetExifMetadataByObjectID :one
SELECT
	object_id,
	taken_at,
	camera_make,
	camera_model,
	lens_model,
	latitude,
	longitude,
	altitude,
	iso,
	aperture_numerator,
	aperture_denominator,
	focal_length_numerator,
	focal_length_denominator,
	exposure_time_numerator,
	exposure_time_denominator,
	orientation
FROM exif_metadata
WHERE object_id = $1
`

func (q *Queries) GetExifMetadataByObjectID(ctx context.Context, objectID int64) (ExifMetadatum, error) {
	row := q.db.QueryRow(ctx, getExifMetadataByObjectID, objectID)
	var i ExifMetadatum
	err := row.Scan(
		&i.ObjectID,
		&i.TakenAt,
		&i.CameraMake,
		&i.CameraModel,
		&i.LensModel,
		&i.Latitude,
		&i.Longitude,
		&i.Altitude,
		&i.Iso,
		&i.ApertureNumerator,
		&i.ApertureDenominator,
		&i.FocalLengthNumerator,
		&i.FocalLengthDenominator,
		&i.ExposureTimeNumerator,
		&i.ExposureTimeDenominator,
		&i.Orientation,
	)
	return i, err
}

const insertExifMetadata = `-- name: InsertExifMetadata :exec
INSERT INTO exif_metadata (
	object_id,
	taken_at,
	camera_make, camera_model, lens_model,
	latitude, longitude, altitude,
	iso,
	aperture_numerator, aperture_denominator,
	focal_length_numerator, focal_length_denominator,
	exposure_time_numerator, exposure_time_denominator,
	orientation
)
VALUES (
	$1,
	$2,
	$3, $4, $5,
	$6, $7, $8,
	$9,
	$10, $11,
	$12, $13,
	$14, $15,
	$16
)
`

type InsertExifMetadataParams struct {
	ObjectID                int64              `json:"object_id"`
	TakenAt                 pgtype.Timestamptz `json:"taken_at"`
	CameraMake              pgtype.Text        `json:"camera_make"`
	CameraModel             pgtype.Text        `json:"camera_model"`
	LensModel               pgtype.Text        `json:"lens_model"`
	Latitude                pgtype.Float8      `json:"latitude"`
	Longitude               pgtype.Float8      `json:"longitude"`
	Altitude                pgtype.Float8      `json:"altitude"`
	Iso                     pgtype.Int4        `json:"iso"`
	ApertureNumerator       pgtype.Int4        `json:"aperture_numerator"`
	ApertureDenominator     pgtype.Int4        `json:"aperture_denominator"`
	FocalLengthNumerator    pgtype.Int4        `json:"focal_length_numerator"`
	FocalLengthDenominator  pgtype.Int4        `json:"focal_length_denominator"`
	ExposureTimeNumerator   pgtype.Int4        `json:"exposure_time_numerator"`
	ExposureTimeDenominator pgtype.Int4        `json:"exposure_time_denominator"`
	Orientation             pgtype.Int4        `json:"orientation"`
}

func (q *Queries) InsertExifMetadata(ctx context.Context, arg InsertExifMetadataParams) error {
	_, err := q.db.Exec(ctx, insertExifMetadata,
		arg.ObjectID,
		arg.TakenAt,
		arg.CameraMake,
		arg.CameraModel,
		arg.LensModel,
		arg.Latitude,
		arg.Longitude,
		arg.Altitude,
		arg.Iso,
		arg.ApertureNumerator,
		arg.ApertureDenominator,
		arg.FocalLengthNumerator,
		arg.FocalLengthDenominator,
		arg.ExposureTimeNumerator,
		arg.ExposureTimeDenominator,
		arg.Orientation,
	)
	return err
}
