// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: image_metadata.sql

package sqlcgen

import (
	"context"
)

const getImageMetadataByObjectID = `-- name: GetImageMetadataByObjectID :one
SELECT
	object_id,
	width,
	height
FROM image_metadata
WHERE object_id = $1
`

func (q *Queries) GetImageMetadataByObjectID(ctx context.Context, objectID int64) (ImageMetadatum, error) {
	row := q.db.QueryRow(ctx, getImageMetadataByObjectID, objectID)
	var i ImageMetadatum
	err := row.Scan(&i.ObjectID, &i.Width, &i.Height)
	return i, err
}

const insertImageMetadata = `-- name: InsertImageMetadata :exec
INSERT INTO image_metadata (object_id, width, height)
VALUES ($1, $2, $3)
`

type InsertImageMetadataParams struct {
	ObjectID int64 `json:"object_id"`
	Width    int32 `json:"width"`
	Height   int32 `json:"height"`
}

func (q *Queries) InsertImageMetadata(ctx context.Context, arg InsertImageMetadataParams) error {
	_, err := q.db.Exec(ctx, insertImageMetadata, arg.ObjectID, arg.Width, arg.Height)
	return err
}
