// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ExifMetadatum struct {
	ObjectID                int64              `json:"object_id"`
	TakenAt                 pgtype.Timestamptz `json:"taken_at"`
	CameraMake              pgtype.Text        `json:"camera_make"`
	CameraModel             pgtype.Text        `json:"camera_model"`
	LensModel               pgtype.Text        `json:"lens_model"`
	Latitude                pgtype.Float8      `json:"latitude"`
	Longitude               pgtype.Float8      `json:"longitude"`
	Altitude                pgtype.Float8      `json:"altitude"`
	Iso                     pgtype.Int4        `json:"iso"`
	ApertureNumerator       pgtype.Int4        `json:"aperture_numerator"`
	ApertureDenominator     pgtype.Int4        `json:"aperture_denominator"`
	FocalLengthNumerator    pgtype.Int4        `json:"focal_length_numerator"`
	FocalLengthDenominator  pgtype.Int4        `json:"focal_length_denominator"`
	ExposureTimeNumerator   pgtype.Int4        `json:"exposure_time_numerator"`
	ExposureTimeDenominator pgtype.Int4        `json:"exposure_time_denominator"`
	Orientation             pgtype.Int4        `json:"orientation"`
}

type ImageMetadatum struct {
	ObjectID int64 `json:"object_id"`
	Width    int32 `json:"width"`
	Height   int32 `json:"height"`
}

type Object struct {
	ID             int64              `json:"id"`
	Sha256         []byte             `json:"sha256"`
	CollisionIndex int32              `json:"collision_index"`
	SizeBytes      int64              `json:"size_bytes"`
	ContentType    string             `json:"content_type"`
	StorageKey     string             `json:"storage_key"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type Upload struct {
	ID           int64              `json:"id"`
	Filename     string             `json:"filename"`
	Status       string             `json:"status"`
	ErrorMessage pgtype.Text        `json:"error_message"`
	ObjectID     pgtype.Int8        `json:"object_id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
