// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: objects.sql

package sqlcgen

import (
	"context"
)

const getObjectByID = `-- name: GetObjectByID :one
SELECT
	id,
	sha256,
	collision_index,
	size_bytes,
	content_type,
	storage_key,
	created_at
FROM objects
WHERE id = $1
`

func (q *Queries) GetObjectByID(ctx context.Context, id int64) (Object, error) {
	row := q.db.QueryRow(ctx, getObjectByID, id)
	var i Object
	err := row.Scan(
		&i.ID,
		&i.Sha256,
		&i.CollisionIndex,
		&i.SizeBytes,
		&i.ContentType,
		&i.StorageKey,
		&i.CreatedAt,
	)
	return i, err
}

const getObjectBySHA256AndCollisionIndex = `-- name: GetObjectBySHA256AndCollisionIndex :one
SELECT
	id,
	sha256,
	collision_index,
	size_bytes,
	content_type,
	storage_key,
	created_at
FROM objects
WHERE sha256 = $1 AND collision_index = $2
`

type GetObjectBySHA256AndCollisionIndexParams struct {
	Sha256         []byte `json:"sha256"`
	CollisionIndex int32  `json:"collision_index"`
}

func (q *Queries) GetObjectBySHA256AndCollisionIndex(ctx context.Context, arg GetObjectBySHA256AndCollisionIndexParams) (Object, error) {
	row := q.db.QueryRow(ctx, getObjectBySHA256AndCollisionIndex, arg.Sha256, arg.CollisionIndex)
	var i Object
	err := row.Scan(
		&i.ID,
		&i.Sha256,
		&i.CollisionIndex,
		&i.SizeBytes,
		&i.ContentType,
		&i.StorageKey,
		&i.CreatedAt,
	)
	return i, err
}

const insertObject = `-- name: InsertObject :one
INSERT INTO objects (sha256, collision_index, size_bytes, content_type, storage_key)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, sha256, collision_index, size_bytes, content_type, storage_key, created_at
`

type InsertObjectParams struct {
	Sha256         []byte `json:"sha256"`
	CollisionIndex int32  `json:"collision_index"`
	SizeBytes      int64  `json:"size_bytes"`
	ContentType    string `json:"content_type"`
	StorageKey     string `json:"storage_key"`
}

func (q *Queries) InsertObject(ctx context.Context, arg InsertObjectParams) (Object, error) {
	row := q.db.QueryRow(ctx, insertObject,
		arg.Sha256,
		arg.CollisionIndex,
		arg.SizeBytes,
		arg.ContentType,
		arg.StorageKey,
	)
	var i Object
	err := row.Scan(
		&i.ID,
		&i.Sha256,
		&i.CollisionIndex,
		&i.SizeBytes,
		&i.ContentType,
		&i.StorageKey,
		&i.CreatedAt,
	)
	return i, err
}

const listObjects = `-- name: ListObjects :many
SELECT
	id,
	sha256,
	collision_index,
	size_bytes,
	content_type,
	storage_key,
	created_at
FROM objects
ORDER BY created_at DESC
`

func (q *Queries) ListObjects(ctx context.Context) ([]Object, error) {
	rows, err := q.db.Query(ctx, listObjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Object
	for rows.Next() {
		var i Object
		if err := rows.Scan(
			&i.ID,
			&i.Sha256,
			&i.CollisionIndex,
			&i.SizeBytes,
			&i.ContentType,
			&i.StorageKey,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listObjectsBySHA256 = `-- name: ListObjectsBySHA256 :many
SELECT
	id,
	sha256,
	collision_index,
	size_bytes,
	content_type,
	storage_key,
	created_at
FROM objects
WHERE sha256 = $1
ORDER BY collision_index
`

func (q *Queries) ListObjectsBySHA256(ctx context.Context, sha256 []byte) ([]Object, error) {
	rows, err := q.db.Query(ctx, listObjectsBySHA256, sha256)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Object
	for rows.Next() {
		var i Object
		if err := rows.Scan(
			&i.ID,
			&i.Sha256,
			&i.CollisionIndex,
			&i.SizeBytes,
			&i.ContentType,
			&i.StorageKey,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
