// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"
)

type Querier interface {
	CreateUpload(ctx context.Context, filename string) (Upload, error)
	GetExifMetadataByObjectID(ctx context.Context, objectID int64) (ExifMetadatum, error)
	GetImageMetadataByObjectID(ctx context.Context, objectID int64) (ImageMetadatum, error)
	GetObjectByID(ctx context.Context, id int64) (Object, error)
	GetObjectBySHA256AndCollisionIndex(ctx context.Context, arg GetObjectBySHA256AndCollisionIndexParams) (Object, error)
	GetUploadByID(ctx context.Context, id int64) (Upload, error)
	InsertExifMetadata(ctx context.Context, arg InsertExifMetadataParams) error
	InsertImageMetadata(ctx context.Context, arg InsertImageMetadataParams) error
	InsertObject(ctx context.Context, arg InsertObjectParams) (Object, error)
	ListObjects(ctx context.Context) ([]Object, error)
	ListObjectsBySHA256(ctx context.Context, sha256 []byte) ([]Object, error)
	ListUploads(ctx context.Context) ([]Upload, error)
	MarkUploadAnalysed(ctx context.Context, arg MarkUploadAnalysedParams) (int64, error)
	MarkUploadCommitted(ctx context.Context, id int64) (int64, error)
	MarkUploadFailed(ctx context.Context, arg MarkUploadFailedParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
