// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: uploads.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUpload = `-- name: CreateUpload :one
INSERT INTO uploads (filename)
VALUES ($1)
RETURNING id, filename, status, error_message, object_id, created_at, updated_at
`

func (q *Queries) CreateUpload(ctx context.Context, filename string) (Upload, error) {
	row := q.db.QueryRow(ctx, createUpload, filename)
	var i Upload
	err := row.Scan(
		&i.ID,
		&i.Filename,
		&i.Status,
		&i.ErrorMessage,
		&i.ObjectID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUploadByID = `-- name: GetUploadByID :one
SELECT
	id,
	filename,
	status,
	error_message,
	object_id,
	created_at,
	updated_at
FROM uploads
WHERE id = $1
`

func (q *Queries) GetUploadByID(ctx context.Context, id int64) (Upload, error) {
	row := q.db.QueryRow(ctx, getUploadByID, id)
	var i Upload
	err := row.Scan(
		&i.ID,
		&i.Filename,
		&i.Status,
		&i.ErrorMessage,
		&i.ObjectID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUploads = `-- name: ListUploads :many
SELECT
	id,
	filename,
	status,
	error_message,
	object_id,
	created_at,
	updated_at
FROM uploads
ORDER BY created_at DESC
`

func (q *Queries) ListUploads(ctx context.Context) ([]Upload, error) {
	rows, err := q.db.Query(ctx, listUploads)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Upload
	for rows.Next() {
		var i Upload
		if err := rows.Scan(
			&i.ID,
			&i.Filename,
			&i.Status,
			&i.ErrorMessage,
			&i.ObjectID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markUploadAnalysed = `-- name: MarkUploadAnalysed :execrows
UPDATE uploads
SET status = 'analysed', object_id = $2, updated_at = NOW()
WHERE id = $1
`

type MarkUploadAnalysedParams struct {
	ID       int64       `json:"id"`
	ObjectID pgtype.Int8 `json:"object_id"`
}

func (q *Queries) MarkUploadAnalysed(ctx context.Context, arg MarkUploadAnalysedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markUploadAnalysed, arg.ID, arg.ObjectID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markUploadCommitted = `-- name: MarkUploadCommitted :execrows
UPDATE uploads
SET status = 'committed', updated_at = NOW()
WHERE id = $1
`

func (q *Queries) MarkUploadCommitted(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, markUploadCommitted, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markUploadFailed = `-- name: MarkUploadFailed :execrows
UPDATE uploads
SET status = 'failed', error_message = $2, updated_at = NOW()
WHERE id = $1
`

type MarkUploadFailedParams struct {
	ID           int64       `json:"id"`
	ErrorMessage pgtype.Text `json:"error_message"`
}

func (q *Queries) MarkUploadFailed(ctx context.Context, arg MarkUploadFailedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markUploadFailed, arg.ID, arg.ErrorMessage)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
